# Generated by Django 5.0.6 on 2024-05-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
    ]
