# Generated by Django 5.0.6 on 2024-05-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_apps', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
