# Generated by Django 5.0.6 on 2024-05-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_apps', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shoe_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
