# Generated by Django 5.0.6 on 2024-05-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_apps', '0011_rename_x_url_profile_twitter_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='colaboration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='color_scheme_1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='color_scheme_2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='color_scheme_3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='shoe_in',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
