# Generated by Django 5.0.6 on 2024-05-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_apps', '0013_rename_shoe_in_post_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
