# Generated by Django 4.1.7 on 2024-05-31 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('future_apps', '0014_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='future_apps.brand'),
        ),
    ]
