# Generated by Django 4.1.7 on 2024-05-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_apps', '0016_alter_post_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
